---
azs:
- name: ((z1_name))
  cpi: ((z1_cpi))
  cloud_properties:
    datacenters:
    - clusters:
      - ((z1_cluster)):
          resource_pool: ((z1_resource_pool))
      name: ((z1_datacenter_name))

networks:
- name: default
  subnets:
  - az: ((z1_name))
    gateway: ((z1_network_gateway))
    dns: ((z1_network_dns_array))
    range: ((z1_network_range))
    reserved: ((z1_network_reserved_array))
    static: ((z1_static_ips))
    cloud_properties:
      name: ((z1_network_name))

resource_pools:
- name: Control Plane
  network: default

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 30_240
- name: minimal
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 10240
- name: small
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 20480
- name: medium
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30720
- name: medium.disk
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 204800
- name: large
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 250600
- name: large.disk
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 501200
- name: large.memory
  cloud_properties:
    cpu: 4
    ram: 10240
    disk: 102400
- name: extra-large
  cloud_properties:
    cpu: 6
    ram: 12288
    disk: 102400
- name: extra-large.disk
  cloud_properties:
    cpu: 6
    ram: 12288
    disk: 501200

disk_types:
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 20480
  name: 20GB
- disk_size: 100240
  name: 100GB
- disk_size: 501200
  name: 500GB
- disk_size: 768000
  name: 750GB
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

vm_extensions:
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: cfcr-master-cloud-properties
- name: cfcr-worker-cloud-properties
- name: 50GB_ephemeral_disk
  cloud_properties:
    disk: 51200
- name: 100GB_ephemeral_disk
  cloud_properties:
    disk: 102400

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: Cluster
  vm_type: small
  network: default
